#!/bin/bash
if [ $# -ne 1 ]; then
    echo "Usage: $0 <url>"
    exit 1
fi
st -e sh -c "wget -O /tmp/tmp.pdf -U 'Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)' $1; exec zathura /tmp/tmp.pdf" & disown
